alias gst='git status'
alias gca='git commit -v -a'
alias gc='git commit -v'
alias gcm='git commit --amend -v'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gcom='git checkout master'
alias ga='git add'
alias gt='git tag'
alias gtd='git tag -d'
alias grvh='git revert HEAD'
alias grsh='git reset HEAD'
alias grshh='git reset --hard'
alias gtype='git cat-file -t'
alias gdump='git cat-file -p'
alias gmm='git merge master'
alias gm='git merge'
alias gp='git pull'
alias gf='git fetch'
alias gmom='git merge origin/master'
alias grh='git reset --hard'
alias gll='git log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --numstat'
alias gl='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
alias gla='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short --all'
alias gcpom='git cherry-pick o/master'
alias gcp='git cherry-pick'
alias gps='git push'
alias gpr='git pull --rebase'
alias gpom='git push origin master'
alias gd='git diff'
alias gdh='git diff HEAD'
alias gdwd='git diff --word-diff'
alias gds='git diff --stat'
alias grv='git remote -v'
